Fixed: cross-device /tmp does not work
mysz/versionup pull request #5
Opened 2019-09-03 14:02 UTC by janpipek

Hi,

I really like what your project does. However, the overwriting of files did not work me. The problem was that the os.rename could not move files across file system boundaries (and I have /tmp on a different partition than /home).

The solution (according to the stackoverflow answer https://stackoverflow.com/a/43967659 - dangerous, I know ;-) ) is to use `shutil.move`. 

What do you think? Would that work for you?

Thanks,
Jan

2019-09-04 16:23 UTC, msztolcman requested changes

2019-09-04 16:23 UTC, msztolcman commented on versionner/version.py
>          except OSError as exc:
Could you please remove also this `try/except` block, because it's not necessary here anymore?

2019-09-04 16:28 UTC, msztolcman commented
Hi Jan,

Yes, this is good solution. In one place there was some workaround for this, and this should also be removed now.
Could you please finish this? And please add yourself to `Authors` section of README, then I'll be glad to merge it :) Thank you!

2019-09-04 19:41 UTC, janpipek commented
Thanks,

you are right, I did the changes maybe too mechanically, not reading what is inside the `except` clause. It should be complete now. I'd be honoured to be mentioned among the contributors, but just putting the name below yours would be a bit asymmetrical in terms of importance.

Cheers,
Jan

2019-09-06 07:56 UTC, msztolcman commented
Hi Jan,

OK, I'm merging your PR, and I am adding new section to README: Contributors, and I'll add you in there :) Thanks again for your PR, it's very important fix :)

2019-09-06 07:57 UTC, merged

2019-09-06 09:27 UTC, janpipek commented
Thanks and you're welcome - at the same time :-)